# Generated by Django 4.2.6 on 2023-10-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_committeemembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemembers',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
